Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.memory = 4096
    libvirt.cpus = 4
    libvirt.machine_type = "virt" # important for aarch64 guests
    libvirt.machine_arch = "aarch64"
    libvirt.loader = "/usr/share/edk2/aarch64/QEMU_EFI.fd"
    libvirt.nvram = "/tmp/vagrant/edk2/myvm_VARS.fd"
    libvirt.cpu_mode = "custom"
    libvirt.cpu_model = "cortex-a72"

    libvirt.input :type => "mouse", :bus => "virtio"
  end

  config.vm.provision "shell", inline: <<-SHELL
    if ! command -v nix &> /dev/null; then
      curl -L https://nixos.org/nix/install | sh
    fi
  SHELL
end
